version: "3.2"
services:
        nginx:
                image: "nginx:latest"
                container_name: "nginx"
                volumes:
                        - docker/nginx/nginx.conf:/etc/nginx/nginx.conf
                networks:
                        - hello
                ports:
                        - "80:80"
networks:
        hello:


