version: "3.2"
services:
        nginx:
                image: "nginx:latest"
                container_name: "nginx"
                volumes:
                        - ./docker/nginx/nginx_product.conf:/etc/nginx/nginx.conf
                        - ./docker/nginx/default_product:/etc/nginx/sites-available/default
                networks:
                        - hello
                ports:
                        - "80:80"
networks:
        hello:


